#!/usr/bin/env bash

[ -d "./plugin" ] && echo "Deleting the redundant \"plugin\" directory."
rm --recursive --force "./plugin"

echo -n "Installing Neovim plugins..."
nvim --headless -c "autocmd User PackerComplete quitall" -c "PackerSync"
echo "Success!"

# FIXME: Does unexpecte behaviour when invoked.
# echo "Installing Neovim LSP servers..."
# nvim --headless -c "MasonToolInstall"
