#!/usr/bin/env bash

docker run --interactive --tty --rm \
  --volume "$(pwd):/root/.config/nvim" \
  # TODO: Add a Docker volume for the "plugins" folder
  # --volume "$(pwd):/root/.config/nvim"
  neovim
