#!/usr/bin/env bash

[ -d "./plugin" ] && echo "The redundant \"/plugin\" directory exists! Deleting it..."
rm --recursive --force "./plugin"

docker run --interactive --tty --rm --volume "$(pwd):/root/.config/nvim" neovim
